### PR TITLE
Fix NFT index in milky-way

### PR DESCRIPTION
**Pull request by cotemper**
### Description

- Synced latest master branch from `metaplex-foundation/metaplex-program-library`.
- Refactored initialize instruction.
- Fixed NFT minting index (start from index 0).

### CODE REVIEW

**Comment by aniiyengar** [comment]
Next time could we make the candy-machine sync a separate PR? It's hard to find the changes you made for com-101

**Comment by aniiyengar** [comment]
Also, one question: will this affect existing milky ways? We have a few deployed on mainnet; will the same token be minted twice for those folks?

**Comment by cotemper** [comment]
> Next time could we make the candy-machine sync a separate PR? It's hard to find the changes you made for com-101

Yeah, sure. This is my bad. I will make a separate/individual PR to sync forked repo.
The comet-101 changes in https://github.com/withcomet/metaplex-program-library/pull/3/commits/d16982469969c4d9092fec577c584068bfe37e64.

**Comment by cotemper** [comment]
> Also, one question: will this affect existing milky ways? We have a few deployed on mainnet; will the same token be minted twice for those folks?

It doesn't affect existing milky ways. The new version of candy-machine includes `set_freeze`, `remove_freeze` and `thaw_nft` instructions. And I think these instructions are not necessary in milky-way program, at least at this stage.

**Pull request merged**
